"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { Card, Container, Section, Button, Input, Badge } from "@crowdstack/ui";
import { ArrowLeft, QrCode, Plus, Edit2, Trash2, Copy, Check, ExternalLink, Download, Eye } from "lucide-react";
import { BeautifiedQRCode } from "@/components/BeautifiedQRCode";

interface DynamicQRCode {
  id: string;
  code: string;
  name: string;
  description?: string | null;
  target_url: string;
  created_at: string;
  updated_at: string;
}

interface QRCodeStats {
  totalScans: number;
  recentScans: number;
  todayScans: number;
  scansByDay: Record<string, number>;
}

export default function QRGeneratorPage() {
  const [qrCodes, setQrCodes] = useState<DynamicQRCode[]>([]);
  const [loading, setLoading] = useState(true);
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  const [baseUrl, setBaseUrl] = useState("");
  const [stats, setStats] = useState<Record<string, QRCodeStats>>({});
  const [loadingStats, setLoadingStats] = useState<Record<string, boolean>>({});
  
  // Form state
  const [formData, setFormData] = useState({
    code: "",
    name: "",
    description: "",
    target_url: "",
  });

  useEffect(() => {
    setBaseUrl(window.location.origin);
    loadQRCodes();
  }, []);

  // Load stats for all QR codes
  useEffect(() => {
    if (qrCodes.length > 0) {
      qrCodes.forEach((qrCode) => {
        loadStats(qrCode.id);
      });
    }
  }, [qrCodes]);

  const loadStats = async (qrCodeId: string) => {
    setLoadingStats((prev) => ({ ...prev, [qrCodeId]: true }));
    try {
      const response = await fetch(`/api/admin/qr-codes/${qrCodeId}/stats`);
      if (response.ok) {
        const data = await response.json();
        setStats((prev) => ({ ...prev, [qrCodeId]: data.stats }));
      }
    } catch (error) {
      console.error("Error loading stats:", error);
    } finally {
      setLoadingStats((prev) => ({ ...prev, [qrCodeId]: false }));
    }
  };

  const loadQRCodes = async () => {
    try {
      const response = await fetch("/api/admin/qr-codes");
      if (response.ok) {
        const data = await response.json();
        setQrCodes(data.qrCodes || []);
      } else {
        console.error("Failed to load QR codes");
      }
    } catch (error) {
      console.error("Error loading QR codes:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      // Code is auto-generated by the API, don't send it
      const response = await fetch("/api/admin/qr-codes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: formData.name,
          description: formData.description || null,
          target_url: formData.target_url,
        }),
      });

      if (response.ok) {
        await loadQRCodes();
        setFormData({ code: "", name: "", description: "", target_url: "" });
        setShowCreateForm(false);
      } else {
        const error = await response.json();
        alert(error.error || "Failed to create QR code");
      }
    } catch (error) {
      console.error("Error creating QR code:", error);
      alert("Failed to create QR code");
    }
  };

  const handleUpdate = async (id: string) => {
    try {
      const response = await fetch(`/api/admin/qr-codes/${id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: formData.name,
          description: formData.description || null,
          target_url: formData.target_url,
        }),
      });

      if (response.ok) {
        await loadQRCodes();
        setEditingId(null);
        setFormData({ code: "", name: "", description: "", target_url: "" });
      } else {
        const error = await response.json();
        alert(error.error || "Failed to update QR code");
      }
    } catch (error) {
      console.error("Error updating QR code:", error);
      alert("Failed to update QR code");
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Are you sure you want to delete this QR code?")) {
      return;
    }

    try {
      const response = await fetch(`/api/admin/qr-codes/${id}`, {
        method: "DELETE",
      });

      if (response.ok) {
        await loadQRCodes();
      } else {
        const error = await response.json();
        alert(error.error || "Failed to delete QR code");
      }
    } catch (error) {
      console.error("Error deleting QR code:", error);
      alert("Failed to delete QR code");
    }
  };

  const startEdit = (qrCode: DynamicQRCode) => {
    setEditingId(qrCode.id);
    setFormData({
      code: qrCode.code,
      name: qrCode.name,
      description: qrCode.description || "",
      target_url: qrCode.target_url,
    });
    setShowCreateForm(false);
  };

  const cancelEdit = () => {
    setEditingId(null);
    setFormData({ code: "", name: "", description: "", target_url: "" });
    setShowCreateForm(false);
  };

  const copyToClipboard = (text: string, code: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(code);
    setTimeout(() => setCopiedCode(null), 2000);
  };

  const getQRUrl = (code: string) => {
    return `${baseUrl}/qr/${code}`;
  };

  const downloadQRCode = async (code: string, name: string) => {
    const qrUrl = getQRUrl(code);
    const size = 512;
    const logoSize = 80;
    const scale = 2; // Use 2x scale for high-quality download
    
    try {
      const QRCode = (await import("qrcode")).default;
      const canvas = document.createElement("canvas");
      canvas.width = size * scale;
      canvas.height = size * scale;
      
      const ctx = canvas.getContext("2d");
      if (!ctx) return;

      // Enable high-quality rendering
      ctx.imageSmoothingEnabled = true;
      ctx.imageSmoothingQuality = "high";
      ctx.scale(scale, scale);

      // Create temporary canvas for QR code
      const tempCanvas = document.createElement("canvas");
      tempCanvas.width = size;
      tempCanvas.height = size;
      
      await QRCode.toCanvas(tempCanvas, qrUrl, {
        width: size,
        margin: 2,
        color: { dark: "#000000", light: "#FFFFFF" },
        errorCorrectionLevel: "H",
      });

      // Draw QR code to main canvas
      ctx.drawImage(tempCanvas, 0, 0, size, size);

      // Draw logo using SVG for crisp rendering
      const centerX = size / 2;
      const centerY = size / 2;
      const logoX = centerX - logoSize / 2;
      const logoY = centerY - logoSize / 2;
      const padding = 4;
      const borderRadius = 8;

      // Draw black background square with rounded corners
      ctx.fillStyle = "#000000";
      ctx.beginPath();
      const x = logoX - padding;
      const y = logoY - padding;
      const w = logoSize + (padding * 2);
      const h = logoSize + (padding * 2);
      ctx.moveTo(x + borderRadius, y);
      ctx.lineTo(x + w - borderRadius, y);
      ctx.quadraticCurveTo(x + w, y, x + w, y + borderRadius);
      ctx.lineTo(x + w, y + h - borderRadius);
      ctx.quadraticCurveTo(x + w, y + h, x + w - borderRadius, y + h);
      ctx.lineTo(x + borderRadius, y + h);
      ctx.quadraticCurveTo(x, y + h, x, y + h - borderRadius);
      ctx.lineTo(x, y + borderRadius);
      ctx.quadraticCurveTo(x, y, x + borderRadius, y);
      ctx.closePath();
      ctx.fill();

      // Create SVG logo and render
      // Based on the actual logo structure with rectangles
      const uniqueId = `logo-${Date.now()}-${Math.random().toString(36).substring(7)}`;
      const svgString = `
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="${logoSize}" height="${logoSize}">
          <defs>
            <linearGradient id="purpleGrad-${uniqueId}" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%" stop-color="#A855F7"/>
              <stop offset="100%" stop-color="#C084FC"/>
            </linearGradient>
            <linearGradient id="blueGrad-${uniqueId}" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%" stop-color="#3B82F6"/>
              <stop offset="100%" stop-color="#60A5FA"/>
            </linearGradient>
          </defs>
          <!-- Bottom layer (widest, blue) -->
          <rect x="4" y="20" width="24" height="3" rx="1" fill="url(#blueGrad-${uniqueId})"/>
          <!-- Third layer (blue) -->
          <rect x="6" y="14" width="20" height="3" rx="1" fill="url(#blueGrad-${uniqueId})"/>
          <!-- Second layer (purple) -->
          <rect x="8" y="8" width="16" height="3" rx="1" fill="url(#purpleGrad-${uniqueId})"/>
          <!-- Top layer (white) -->
          <rect x="10" y="2" width="12" height="3" rx="1" fill="white"/>
        </svg>
      `;

      const logo = new Image();
      const svgBlob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
      const url = URL.createObjectURL(svgBlob);
      
      logo.onload = () => {
        ctx.drawImage(logo, logoX, logoY, logoSize, logoSize);
        URL.revokeObjectURL(url);
        
        // Download
        const pngUrl = canvas.toDataURL("image/png");
        const downloadLink = document.createElement("a");
        downloadLink.href = pngUrl;
        downloadLink.download = `qr-code-${code}.png`;
        document.body.appendChild(downloadLink);
        downloadLink.click();
        document.body.removeChild(downloadLink);
      };

      logo.onerror = () => {
        // Fallback to PNG if SVG fails
        const fallbackImg = new Image();
        fallbackImg.crossOrigin = "anonymous";
        fallbackImg.onload = () => {
          ctx.drawImage(fallbackImg, logoX, logoY, logoSize, logoSize);
          const pngUrl = canvas.toDataURL("image/png");
          const downloadLink = document.createElement("a");
          downloadLink.href = pngUrl;
          downloadLink.download = `qr-code-${code}.png`;
          document.body.appendChild(downloadLink);
          downloadLink.click();
          document.body.removeChild(downloadLink);
        };
        fallbackImg.src = "/logos/crowdstack-icon-tricolor-on-transparent.png";
        URL.revokeObjectURL(url);
      };

      logo.src = url;
    } catch (error) {
      console.error("Error generating QR code for download:", error);
      alert("Failed to generate QR code for download");
    }
  };

  return (
    <Section spacing="lg">
      <Container>
        {/* Header */}
        <div className="mb-8">
          <Link
            href="/admin"
            className="inline-flex items-center gap-2 text-sm text-secondary hover:text-primary mb-4"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Admin
          </Link>
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-accent-secondary/20 rounded-lg border border-accent-secondary/30">
                <QrCode className="w-6 h-6 text-accent-secondary" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-primary">Dynamic QR Code Generator</h1>
                <p className="text-sm text-secondary">
                  Create reusable QR codes that can point to different URLs dynamically
                </p>
              </div>
            </div>
            {!showCreateForm && !editingId && (
              <Button onClick={() => setShowCreateForm(true)}>
                <Plus className="h-4 w-4 mr-2" />
                Create QR Code
              </Button>
            )}
          </div>
        </div>

        {/* Create/Edit Form */}
        {(showCreateForm || editingId) && (
          <Card className="!p-6 mb-8">
            <h2 className="text-lg font-semibold text-primary mb-4">
              {editingId ? "Edit QR Code" : "Create New QR Code"}
            </h2>
            <form
              onSubmit={editingId ? (e) => { e.preventDefault(); handleUpdate(editingId); } : handleCreate}
              className="space-y-4"
            >
              {editingId && (
                <div>
                  <label className="block text-sm font-medium text-primary mb-2">
                    Code
                  </label>
                  <Input
                    value={formData.code}
                    readOnly
                    disabled
                    className="font-mono bg-raised"
                  />
                  <p className="text-xs text-secondary mt-1">
                    Unique identifier (auto-generated, cannot be changed)
                  </p>
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-primary mb-2">
                  Name <span className="text-accent-error">*</span>
                </label>
                <Input
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder="Venue Window Sign"
                  required
                />
                <p className="text-xs text-secondary mt-1">
                  Human-readable name for this QR code
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-primary mb-2">
                  Description
                </label>
                <textarea
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  placeholder="Optional description or notes about this QR code"
                  rows={3}
                  className="w-full px-3 py-2 bg-raised border border-border-subtle rounded-lg text-primary placeholder-secondary focus:outline-none focus:ring-2 focus:ring-accent-primary/50 focus:border-accent-primary/50 resize-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-primary mb-2">
                  Target URL <span className="text-accent-error">*</span>
                </label>
                <Input
                  type="url"
                  value={formData.target_url}
                  onChange={(e) => setFormData({ ...formData, target_url: e.target.value })}
                  placeholder="https://example.com/event/register?ref=venue"
                  required
                />
                <p className="text-xs text-secondary mt-1">
                  The URL this QR code will redirect to. You can change this anytime without reprinting the QR code.
                </p>
              </div>

              <div className="flex gap-3 pt-2">
                <Button type="submit">
                  {editingId ? "Update QR Code" : "Create QR Code"}
                </Button>
                <Button type="button" variant="secondary" onClick={cancelEdit}>
                  Cancel
                </Button>
              </div>
            </form>
          </Card>
        )}

        {/* QR Codes List */}
        {loading ? (
          <div className="text-center py-12">
            <p className="text-secondary">Loading QR codes...</p>
          </div>
        ) : qrCodes.length === 0 ? (
          <Card className="!p-12 !border-dashed">
            <div className="text-center">
              <QrCode className="h-12 w-12 text-muted mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-primary mb-2">
                No QR codes yet
              </h3>
              <p className="text-sm text-secondary mb-6">
                Create your first dynamic QR code to get started
              </p>
              <Button onClick={() => setShowCreateForm(true)}>
                <Plus className="h-4 w-4 mr-2" />
                Create QR Code
              </Button>
            </div>
          </Card>
        ) : (
          <Card className="!p-0 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-raised border-b border-border-subtle">
                  <tr>
                    <th className="text-left px-6 py-3 text-xs font-medium text-secondary uppercase tracking-widest">QR Code</th>
                    <th className="text-left px-6 py-3 text-xs font-medium text-secondary uppercase tracking-widest">Name / Code</th>
                    <th className="text-left px-6 py-3 text-xs font-medium text-secondary uppercase tracking-widest">Description</th>
                    <th className="text-left px-6 py-3 text-xs font-medium text-secondary uppercase tracking-widest">Target URL</th>
                    <th className="text-center px-6 py-3 text-xs font-medium text-secondary uppercase tracking-widest">Stats</th>
                    <th className="text-right px-6 py-3 text-xs font-medium text-secondary uppercase tracking-widest">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border-subtle">
                  {qrCodes.map((qrCode) => (
                    <tr key={qrCode.id} className="hover:bg-raised/50 transition-colors">
                      <td className="px-6 py-4">
                        <div className="bg-white rounded p-2 w-20 h-20 flex items-center justify-center">
                          <BeautifiedQRCode
                            url={getQRUrl(qrCode.code)}
                            size={80}
                            logoSize={16}
                          />
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <div>
                          <p className="font-semibold text-primary">{qrCode.name}</p>
                          <p className="text-xs font-mono text-secondary mt-1">{qrCode.code}</p>
                          <p className="text-xs text-muted mt-1">
                            Updated {new Date(qrCode.updated_at).toLocaleDateString()}
                          </p>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <p className="text-sm text-secondary max-w-xs truncate">
                          {qrCode.description || <span className="text-muted italic">No description</span>}
                        </p>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2 max-w-xs">
                          <p className="text-xs font-mono text-secondary truncate">{qrCode.target_url}</p>
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => window.open(qrCode.target_url, "_blank")}
                            className="flex-shrink-0"
                          >
                            <ExternalLink className="h-3 w-3" />
                          </Button>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        {stats[qrCode.id] ? (
                          <div className="flex items-center gap-4 justify-center">
                            <div className="text-center">
                              <p className="text-sm font-bold text-primary">{stats[qrCode.id].totalScans}</p>
                              <p className="text-[10px] text-secondary">Total</p>
                            </div>
                            <div className="text-center">
                              <p className="text-sm font-bold text-accent-secondary">{stats[qrCode.id].recentScans}</p>
                              <p className="text-[10px] text-secondary">30d</p>
                            </div>
                            <div className="text-center">
                              <p className="text-sm font-bold text-accent-success">{stats[qrCode.id].todayScans}</p>
                              <p className="text-[10px] text-secondary">Today</p>
                            </div>
                          </div>
                        ) : loadingStats[qrCode.id] ? (
                          <span className="text-xs text-secondary">Loading...</span>
                        ) : (
                          <span className="text-xs text-muted">—</span>
                        )}
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2 justify-end">
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => copyToClipboard(getQRUrl(qrCode.code), qrCode.code)}
                            title="Copy QR URL"
                          >
                            {copiedCode === qrCode.code ? (
                              <Check className="h-4 w-4 text-accent-success" />
                            ) : (
                              <Copy className="h-4 w-4" />
                            )}
                          </Button>
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => downloadQRCode(qrCode.code, qrCode.name)}
                            title="Download"
                          >
                            <Download className="h-4 w-4" />
                          </Button>
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => startEdit(qrCode)}
                            title="Edit"
                          >
                            <Edit2 className="h-4 w-4" />
                          </Button>
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => handleDelete(qrCode.id)}
                            title="Delete"
                          >
                            <Trash2 className="h-4 w-4 text-accent-error" />
                          </Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        )}
      </Container>
    </Section>
  );
}

